apiVersion: v1
kind: ConfigMap
metadata:
  name: map-conf
data:
  env: |
    APP_PORT=3000
    RABBITMQ_HOST=rabbitmq-service
    RABBITMQ_USER=admin
    RABBITMQ_PASSWORD=admin
    MYSQL_HOST=map-mysql-service
    MYSQL_USER=root
    MYSQL_PASSWORD=root
