version: "3"

services:
  goapp_simulator:
    build: .
    container_name: simulator
    volumes:
      - .:/app
    networks:
      - rabbitmq_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  rabbitmq_network:
    external: true
