version: "3"

services:
  frontend:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-mapping-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3002
    ports:
      - 3002:3002
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  app-network:
    driver: bridge
