apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      nodePort: 30081
    - name: amqp
      protocol: TCP
      port: 5672
      nodePort: 30082
