apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |
    RABBITMQ_DEFAULT_USER="admin"
    RABBITMQ_DEFAULT_PASS="admin"
    RABBITMQ_DEFAULT_HOST="rabbitmq-service"
    RABBITMQ_DEFAULT_PORT="5672"
    RABBITMQ_DEFAULT_VHOST="/"
    RABBITMQ_CONSUMER_QUEUE="micro-simulator/orders-new"
    RABBITMQ_DESTINATION_POSITIONS_EX="amq.direct"
    RABBITMQ_DESTINATION_ROUTING_KEY="mapping.new-position"
