apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: sidartasilva/codelivery-simulator:v3
          envFrom:
            - configMapRef:
                name: simulator-conf
          volumeMounts:
            - name: simulator-conf
              subPath: .env
              mountPath: /app/.env
      volumes:
        - name: simulator-conf
          configMap:
            name: simulator-conf
            items:
              - key: env
                path: .env
